scope "intermine.icons", {
    Yes: "icon-star",
    No: "icon-star-empty",
    Script: "icon-beaker",
    Export: "icon-download-alt",
    Remove: "icon-minus-sign",
    Check: "icon-circle",
    UnCheck: "icon-circle-blank",
    CheckUnCheck: "icon-circle icon-circle-blank",
    Add: "icon-plus-sign",
    Move: "icon-reorder",
    More: "icon-plus-sign-alt",
    Filter: "icon-filter",
    Summary: "icon-bar-chart",
    Undo: "icon-undo",
    Columns: "icon-table",
    Collapsed: "icon-angle-right",
    Expanded: "icon-angle-down",
    MoveDown: "icon-angle-down",
    MoveUp: "icon-angle-up",
    ExpandCollapse: "icon-angle-right icon-angle-down",
    Help: "icon-question-sign",
    ReverseRef: 'icon-retweet',
    Edit: 'icon-cogs',
    Download: 'icon-file-alt',
    ClipBoard: 'icon-paper-clip',
    tsv: 'icon-th',
    csv: 'icon-th',
    xml: 'icon-xml',
    json: 'icon-json'
}


